config/routes.rb
ALLOW_DOTS ||= /[a-zA-Z0-9\-_.:]+/

TDL::Application.routes.draw do
  root :to => "catalog#index"
  match '/imageviewer/:id', :to => 'imageviewer#show', :constraints => {:id => /.*/}, :as =>'imageviewer'
  match '/bookreader/:id', :to => 'imageviewer#show_book', :constraints => {:id => /.*/}, :as =>'bookreader'
  match '/robots.txt', :to => 'application#robots'

    resources :catalog, :only => [:show, :update], :constraints => { :id => ALLOW_DOTS, :format => false }
    Blacklight::Routes.new(self, {}).catalog
    Blacklight::Routes.new(self, {}).search_history
    resources :unpublished, :only => :index
    resources :solr_document,  :path => 'catalog', :controller => 'catalog', :only => [:show, :update]
    resources :downloads, :only =>[:show], :constraints => { :id => ALLOW_DOTS
   }
   resources :bookmarks, :path => 'catalog'
   resources :search_history, :path => 'search_history', :only => [:index,:show]

    HydraHead.add_routes(self)

  ele = {:object_type_sim => ['Generic Objects'], :names_sim => ['American Antiquarian Society']}
   match '/election_datasets', :to => 'catalog#index', :f => ele, :q=>'', :search_field=>'all_fields'
   match '/search', :to => 'catalog#search', :constraints => {:id => /.*/}
   match '/catalog/facet/:id', :to => 'catalog#facet', :constraints => {:id => ALLOW_DOTS}
   match '/catalog/transcriptonly/:id', :to => 'catalog#transcriptonly', :constraints => {:id => /.*/}, :as =>'transcriptonly'
   match '/advanced/facet/:id', :to => 'advanced#facet', :constraints => {:id => /.*/}, :as =>'advanced'
   match "/about" => "about#index"
   match "/contact" => "contact#show"
   match "/about/:action" => "about"
   match '/file_assets/medium/:id', :to => 'local_file_assets#showMedium', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/advanced/:id', :to => 'local_file_assets#showAdvanced', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/archival/:id', :to => 'local_file_assets#showArchival', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/thumb/:id', :to => 'local_file_assets#showThumb', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/transcript/:id', :to => 'local_file_assets#showTranscript', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/rcr/:id', :to => 'local_file_assets#showRCR', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/generic/:id/:index', :to => 'local_file_assets#showGeneric', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/dimensions/:id', :to => 'local_file_assets#dimensions', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/image_overlay/:id', :to => 'local_file_assets#image_overlay', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/image_gallery/:id/:start/:number', :to => 'local_file_assets#image_gallery', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/webm/:id', :to => 'local_file_assets#showWebm', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/local_file_assets/:id', :to => 'local_file_assets#show', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/file_assets/:id', :to => 'local_file_assets#show', :constraints => {:id => /.*/}, :as =>'file_asset'
   match '/pdf_pages/:id/metadata', :to => 'pdf_pages#dimensions', :constraints => {:id => /.*/}, :as =>'pdf_page'
   match '/pdf_pages/:id/:pageNumber', :to => 'pdf_pages#show', :constraints => {:id => /.*/, :pageNumber => /.*/}, :as =>'pdf_page'
   match '/catalog/tei/:id/chapter/:chapter', :to => 'catalog#teireader', :constraints => {:id => /.*/,:chapter => /.*/}, :as =>'teireader'
   match '/catalog/tei/:id', :to => 'catalog#teireader', :constraints => {:id => /.*/}, :as =>'teireader'
   match '/catalog/ead/:id/:item_id', :to => 'catalog#eadinternal', :constraints => {:id => /.*/, :item_id => /.*/}, :as =>'eadinternal'
   match '/catalog/ead/:id', :to => 'catalog#eadoverview', :constraints => {:id => /.*/}, :as =>'eadoverview'
   match "feedback", :to => "feedback#show"    
   match "feedback/complete", :to => "feedback#complete"
   devise_for :users

   mount Hydra::RoleManagement::Engine => '/'
   mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/views/shared/_add_to_list.html.erb
<a class="list-add" href="#" data-pid="<%= j @document_fedora.pid %>"
   data-identifier="<%= j @document_fedora.pid.gsub(/[^0-9a-z ]/i, '') %>"
   <% if @document_fedora.class == TuftsEAD %>
    data-itemtitle="<%=strip_tags(metadata[:titles].first) unless metadata[:titles].empty? %>"
   <% else %>
     data-itemtitle="<%= strip_tags(get_ead_title(@document_fedora, false)) %>"
   <% end %>
   <% if defined? series_title %>
     data-itemsubtitle="<%= strip_tags(series_title) %>"
   <% else %>
     data-itemsubtitle="<%=strip_tags(metadata[:titles].first) unless metadata[:titles].empty? %>"
   <% end %>
   data-site="DCA"
   data-author="<%= strip_tags(metadata[:creators].first) unless metadata[:creators].empty? %>"
   data-itemauthor="<%= strip_tags(metadata[:creators].first) unless metadata[:creators].empty? %>"
   data-iteminfo2="<%= strip_tags(metadata[:creators].first) unless metadata[:creators].empty? %>"
   data-iteminfo3="<%= strip_tags(metadata[:citable_urls].first) unless metadata[:citable_urls].empty? %>"


   <% if defined? series_id %>
     data-itemvolume="<%= strip_tags(series_id) %>"
     data-callnumber="<%= strip_tags(series_id.split('.').first) unless metadata[:sources].empty? %>"
   <% else %>
     data-itemvolume="<%= j @document_fedora.pid %>"
     <% if defined? unitid %>
       data-callnumber="<%= strip_tags(unitid) %>"
     <% else %>
       data-callnumber="<%= strip_tags(metadata[:sources].first) unless metadata[:sources].empty? %>"
     <% end %>
   <% end %>
   data-itemdate="<%= strip_tags(metadata[:dates].first) unless metadata[:dates].nil? %>">
  <i class="icon-plus-sign"/></i>&nbsp;Add to List
</a>

app/views/shared/_creator.html.erb
<% unless metadata[:creators].empty? %>
    <dd>Creator</dd>
    <% metadata[:creators].each do |creator| %>
        <dt><%= raw creator.text %></dt>
    <% end %>
<% end %>

app/views/shared/_format.html.erb
<% unless metadata[:formats].empty? %>
    <dd>Format</dd>
    <% metadata[:formats].each do |format| %>
        <dt><%= raw format.text %></dt>
    <% end %>
<% end %>

app/views/shared/_header_elements.html.erb
<% metadata[:titles].each do |title| %>
    <h2><%= raw title %></h2>
<% end %>
<% metadata[:creators].each do |creator| %>
    <%= raw creator %>
    <br>
<% end %>
<% unless metadata[:dates].nil? || metadata[:dates].empty? || metadata[:is_parts_of].include?('Tufts University Permanent Collection') || metadata[:is_parts_of].include?('Tufts University Permanent Collection.') %>
    <% metadata[:dates].each do |date| %>
        <%= raw date %>
        <br>
    <% end %>
<% else %>
    <% metadata[:temporals].each do |temporal| %>
        <%= raw temporal %>
        <br>
    <% end %>
<% end %>

app/views/shared/_metadata_pane.html.erb
<%= render :partial => 'shared/description', :locals => {:metadata => metadata} %>
<dl id="metadatapane">
  <!-- in collection -->
  <!-- illustration appears in -->
  <%= get_collection_link_for_object() %>
  <%= get_appears_in_text() %>
  <%= render :partial => 'shared/subjects', :locals => {:metadata => metadata} %>
  <%= render :partial => 'shared/genre', :locals => {:metadata => metadata} %>
  <%= render :partial => 'shared/citation', :locals => {:metadata => metadata} %>
  <%= render :partial => 'shared/original_publication', :locals => {:metadata => metadata} %>

</dl>
<% if defined? is_image %>
  <%= render :partial => 'shared/metadata_well', :locals => {:metadata => metadata, :is_image => is_image} %>
<% else %>
  <%= render :partial => 'shared/metadata_well', :locals => {:metadata => metadata} %>
<% end %>
<!-- tooltip-demo well -->

app/views/shared/_metadata_well.html.erb
<div class="tooltip-demo well">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="noborder">
    <tr>
      <td width="50">ID:</td>
      <td><%= params[:id] %></td>
    </tr>
    <tr>
      <td>To Cite:</td>
      <td><a href="http://sites.tufts.edu/dca/about-us/research-help/reproductions-and-use/">DCA Citation Guide</a></td>
    </tr>
    <% unless metadata[:rights].empty? %>
        <tr>
          <td>Usage:</td>
          <% metadata[:rights].each do |rights| %>
              <td><a href="<%= raw rights %>">Detailed Rights</a></td>
          <% end %>
        </tr>
    <% end %>


  </table>
  <% if defined? is_image %>
        <p>To request a high-resolution image, choose Add to List.</p>

  <% end %>
</div>

app/views/shared/_original_publication.html.erb
<% unless metadata[:citations].empty? %>
    <dd>Original publication</dd>
    <% metadata[:citations].each do |citation| %>
        <dt><%= raw citation %></dt>
    <% end %>
<% end %>

app/views/shared/_publisher.html.erb
<% unless metadata[:publishers].empty? %>
    <dd>Publisher</dd>
    <% metadata[:publishers].each do |publisher| %>
        <dt><%= raw publisher.text %></dt>
    <% end %>
<% end %>

app/views/shared/_search_bar.html.erb
  <div class="span8 offset3">
      <%= render :partial => 'shared/search_form' %>
  </div>

app/views/shared/_search_form.html.erb
<%= form_tag catalog_index_path, :class => "form-horizontal", :method => :get do %>
    <i class="icon-search"></i>  <%= text_field_tag :q, params[:q], :class => "q input-medium",:placeholder=>"Search for" %>
    <% unless search_fields.empty? %>
        <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => "Targeted search options", :class => "span2") %>
    <% end %>
    <button type="submit" class="btn">Search</button>&nbsp;
    <% unless "search" == @current_action %>
        <%= link_to 'Advanced Search', params.merge(:controller => "advanced", :action => "index"), :class => "advanced_search" %>
    <% end %>
<% end %>

app/views/shared/_subjects.html.erb
<% unless metadata[:subjects].empty? %>
    <dd>Subjects</dd>
    <% metadata[:subjects].each do |subject| %>
        <dt><%= link_to((raw subject), "/?&all_fields=&author=&collection=&description=&organization=&people=&place=&search_field=advanced&title=&utf8=✓&year_end=&year_start=&topic="+ (raw subject)) %></dt>
                                         
    <% end %>
<% end %>

app/views/shared/_subnav.html.erb
<div class="subnav">
  <% if ("index" == @current_action && "advanced" != @current_controller) || "about" == @current_action || "contact" == @current_action %>
    <%= render :partial =>"shared/search_bar" %>
  <% elsif "eadoverview" == @current_action %>
    <div class="span6" style="padding-top: 5px;">
      <a href="<%= Tufts::EADMethods.collection_url(@document_fedora) %>"><i class="icon-arrow-left"></i>&nbsp;Collection Home</a>
    </div>
    <div class="span6 pull-right download_links" style="display: none;">    <!-- display: none; for now until pdfs become available -->
      <a href="/file_assets/pdf/<%= params[:id] %>" onClick="ga('send', 'event', 'Attachment', 'Download', '<%= params[:id] %>');"><i class="icon-file"/></i>&nbsp;Download Collection Guide (PDF)</a>
    </div>
  <% elsif "eadinternal" == @current_action %>
    <div class="span12" style="padding-top: 5px;">
      <a href="<%= Tufts::EADMethods.finding_aid_url(@document_fedora) %>"><i class="icon-arrow-left"></i>&nbsp;<%= @collection_title %></a> > <%= @series_full_title %>
    </div>
  <% elsif "teireader" == @current_action %>
    <div class="span12" style="padding-top: 5px;">
      <a href="/catalog/<%= params[:id] %>"><i class="icon-arrow-left"></i>&nbsp;Back to Book Home</a>
    </div>
  <% elsif "transcriptonly" == @current_action %>
    <% if @document_fedora.relationships(:has_model).include?("info:fedora/afmodel:TuftsVideo") %>
      <div class="span6" style="padding-top: 5px;">
        <a href="/catalog/<%= params[:id] %>"><i class="icon-arrow-left"></i>&nbsp;Back to Video Player</a>
      </div>
      <div class="span6 pull-right download_links">
        <a href="/file_assets/<%= params[:id] %>" onClick="ga('send', 'event', 'Attachment', 'Download', '<%= params[:id] %>');"><i class="icon-film"/></i>&nbsp;Download Video File</a>&nbsp;&nbsp;<a href="/file_assets/transcript/<%= params[:id] %>"><i class="icon-file"/></i>&nbsp;Download Transcript</a>
      </div>
    <% else %>
      <div class="span6" style="padding-top: 5px;">
        <a href="/catalog/<%= params[:id] %>"><i class="icon-arrow-left"></i>&nbsp;Back to Audio Player</a>
      </div>
      <div class="span6 pull-right download_links">
        <a href="/file_assets/<%= params[:id] %>" onClick="ga('send', 'event', 'Attachment', 'Download', '<%= params[:id] %>');"><i class="icon-headphones"/></i>&nbsp;Download Audio File</a>&nbsp;&nbsp;<a href="/file_assets/transcript/<%= params[:id] %>"><i class="icon-file"/></i>&nbsp;Download Transcript</a>
      </div>
    <% end %>
  <% elsif "facet" == @current_action %>
    <div class="span5" style="padding-top: 5px;">
    <% if refered_from_our_site? %>
      <a href="<%= request.env["HTTP_REFERER"]%>"><i class="icon-arrow-left"></i>&nbsp;Back</a>
    <% end %>
    </div>
  <% elsif !@document.nil? %>
    <% format = document_partial_name(@document) %>
    <div class="span5" style="padding-top: 5px;">
      <% if refered_from_our_site? %>
        <i class="icon-arrow-left"></i>&nbsp;<%= link_back_to_catalog(:label=>'Back to Search Results') %>
      <% end %>
    </div>
    <%= render :partial=>"#{format}/subnav"%>
  <% end %>
</div>

app/views/shared/_temporal.html.erb
<% unless metadata[:temporals].empty? %>
    <dd>Temporal</dd>
    <% metadata[:temporals].each do |temporal| %>
        <dt><%= raw temporal.text %></dt>
    <% end %>
<% end %>

app/views/shared/_type.html.erb
<% unless metadata[:types].empty? %>
    <dd>Type</dd>
    <% metadata[:types].each do |type| %>
        <dt><%= raw type.text %></dt>
    <% end %>
<% end %>